version: 2
plan:
  project-key: SPRIN
  key: MYDEPLOY
  name: My Deploy
stages:
- Stage 1:
    jobs:
    - Job 1
Job 1:
  tasks:
  - ssh:
      host: 20.127.63.130
      command: "helm repo add helm-wo-secret-helm https://venkatesan.jfrog.io/artifactory/api/helm/helm-wo-secret-helm --username venkatesan06.mvm@gmail.com --password AP6t1z5AmesHu5Y8xZUEJjBj7o3\r\nhelm repo update"
      authentication:
        username: azureuser
        shared-credentials: openshift-ssh
variables:
  jfrog_password: BAMSCRT@0@0@nXjkn/IPBvrcy563dgMQYQ== 
  jfrog_user: venkatesan06.mvm@gmail.com

